/**
 * WordPress dependencies
 */
import { rawHandler } from '@wordpress/blocks';
import { registerCoreBlocks } from '@wordpress/block-library';

/**
 * Internal dependencies
 */
import BlockCompare from '../';
import { ExperimentalBlockEditorProvider } from '../../provider';

const blockToBlocks = ( block ) =>
	rawHandler( {
		HTML: block.originalContent,
	} );

// For the purpose of this story, we need to register the core block samples.
registerCoreBlocks();
// const block = [ createBlock( 'core/paragraph' ) ];
const block = {
	clientId: 'df1ce652-9d7a-4564-8d2f-4176222eee67',
	name: 'core/spacer',
	isValid: false,
	originalContent:
		'<div styless="height:100px" aria-hidden="true" class="wp-block-spacer"></div>',
	validationIssues: [
		{
			args: [ 'Encountered unexpected attribute `%s`.', 'styless' ],
		},
		{
			args: [
				'Block validation failed for `%s` (%o).\n\nContent generated by `save` function:\n\n%s\n\nContent retrieved from post body:\n\n%s',
				'core/spacer',
				{
					name: 'core/spacer',
					icon: {
						src: {
							type: {},
							key: null,
							ref: null,
							props: {
								viewBox: '0 0 24 24',
								xmlns: 'http://www.w3.org/2000/svg',
								children: {
									key: null,
									ref: null,
									props: {
										d: 'M7 18h4.5v1.5h-7v-7H6V17L17 6h-4.5V4.5h7v7H18V7L7 18Z',
									},
									_owner: null,
									_store: {},
								},
							},
							_owner: null,
							_store: {},
						},
					},
					keywords: [],
					attributes: {
						height: {
							type: 'string',
							default: '100px',
						},
						width: {
							type: 'string',
						},
						lock: {
							type: 'object',
						},
						metadata: {
							type: 'object',
						},
						className: {
							type: 'string',
						},
						style: {
							type: 'object',
						},
						anchor: {
							type: 'string',
							source: 'attribute',
							attribute: 'id',
							selector: '*',
						},
						blockCommentId: {
							type: 'number',
						},
					},
					providesContext: {},
					usesContext: [ 'orientation' ],
					selectors: [],
					supports: {
						anchor: true,
						spacing: {
							margin: [ 'top', 'bottom' ],
							defaultControls: {
								margin: true,
							},
						},
						interactivity: {
							clientNavigation: true,
						},
					},
					styles: [],
					blockHooks: [],
					apiVersion: 3,
					title: 'Spacer',
					description:
						'Add white space between blocks and customize its height.',
					category: 'design',
					variations: [],
					transforms: {
						to: [
							{
								type: 'block',
								blocks: [ 'core/separator' ],
							},
						],
					},
					deprecated: [
						{
							attributes: {
								height: {
									type: 'number',
									default: 100,
								},
								width: {
									type: 'number',
								},
								lock: {
									type: 'object',
								},
								className: {
									type: 'string',
								},
								metadata: {
									type: 'object',
								},
								blockCommentId: {
									type: 'number',
								},
							},
						},
					],
				},
				'<div style="height:100px" aria-hidden="true" class="wp-block-spacer"></div>',
				'<div styless="height:100px" aria-hidden="true" class="wp-block-spacer"></div>',
			],
		},
	],
	__unstableBlockSource: {
		blockName: 'core/spacer',
		attrs: {},
		innerBlocks: [],
		innerHTML:
			'\n<div styless="height:100px" aria-hidden="true" class="wp-block-spacer"></div>\n',
		innerContent: [
			'\n<div styless="height:100px" aria-hidden="true" class="wp-block-spacer"></div>\n',
		],
	},
	attributes: {
		height: '100px',
	},
	innerBlocks: [],
};

/**
 * A comparison component that shows two blocks side-by-side along with differences in HTML highlighted.
 * This is typically used to show the current block and the results of converting the block.
 */
const meta = {
	title: 'BlockEditor/BlockCompare',
	component: BlockCompare,
	decorators: [
		( Story ) => (
			<ExperimentalBlockEditorProvider block={ block }>
				<Story />
			</ExperimentalBlockEditorProvider>
		),
	],
	argTypes: {
		block: {
			control: {
				type: 'object',
			},
			description: 'The original object to compare against.',
		},
		onKeep: {
			control: {
				type: 'none',
			},
			description: 'Callback when the original block is required.',
		},
		onConvert: {
			control: {
				type: 'none',
			},
			description: 'Callback when the converted block is required.',
		},
		convertor: {
			control: {
				type: 'none',
			},
			description:
				'A function that returns a new, converted, block when supplied an existing block. The conversion may fix or alter the block in a way that helps with an invalid block.',
		},
		convertButtonText: {
			control: {
				type: 'text',
			},
			description: 'Text to show in the convert button.',
		},
	},
};
export default meta;

export const Default = {
	args: {
		block,
		onKeep: () => {},
		onConvert: () => {},
		convertor: blockToBlocks,
		convertButtonText: 'Convert',
	},
};
