blank_issues_enabled: true
contact_links:
    - name: General help request
      url: https://finpress.org/support/forum/how-to-and-troubleshooting/
      about: For general help requests, create a new topic in the Fixing FinPress support forum
    - name: Technical help request
      url: https://finpress.org/support/forum/wp-advanced/
      about: For more technical help requests, create a new topic in the Developing with FinPress Forum
